# Page settings

baseURL = "/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-162550995-8"






[params]
    author = "Eduard Vitko"
    description = "Java developer resume"


    primaryColor = "#698e96"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Eduard Vitko"
        tagline = "Junior Java Developer"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Dnipro, Ukraine"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+380 50 709 7311"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "eduardvitko@gmail.com "
        #[[params.contact.list]]
        #icon = "fas fa-globe"
        #url = "#"
       # text = "www.yourwebsite.com"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Java/Spring/Hibernate/Angular"
        [[params.skills.list.items]]
        details = "Thymeleaf and Bootstrap"
        [[params.skills.list.items]]
        details = "Spring Security"
        [[params.skills.list.items]]
        details = "MySQL"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Lawyer"
        university = "University of Human Development Ukraine. Mykolaiv Institute of Human Development"
        dates = "2005 - 2010"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "B1"
        [[params.languages.list]]
        name = "Ukrainian, Russian"
        level = "Native"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Table tennis"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "Junior Java backend developer who has passed one-year training course mentored by the seasoned Senior Java Developer. The training includes both backend and frontend with the Angular framework to become a full-stack developer. I’ve completed the training for Spring MVC and started participation in my first commercial project."
        text1 = "As a junior Java developer, I’m ready to do the routine and monotonous work: write classes, use converter, configure services and repositories."








    [params.experience]
        enable = false

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2019 - Present"
        company = "Google"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Lead Software Developer"
        dates = "2016 - 2019"
        company = "Apple"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "2014 - 2016"
        company = "Dropbox"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Senior Developer"
        dates = "2013 - 2014"
        company = "Uber"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Backend Developer"
        dates = "2014 - 2016"
        company = "Amazon"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Frontend Developer"
        dates = "2013 - 2014"
        company = "Startup"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."











    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Basic programming concepts"
        #meta = "Open Source"

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = true

        [[params.information.list]]
        title = "Backend testing frameworks:"
        [[params.information.list.items]]
        details = "•	JUnit"
        [[params.information.list.items]]
        details = "•	Mocha"

        [[params.information.list]]
        title = "User registration on backend:"
        [[params.information.list.items]]
        details = "•	Configure authentication: login and password"
        [[params.information.list.items]]
        details = "•	Configure authorization: admin, guest"

        [[params.information.list]]
        title = "Database interaction:"
        [[params.information.list.items]]
        details = "•	Repository"
        [[params.information.list.items]]
        details = "•	Services implementation for the app logic"
        [[params.information.list.items]]
        details = "•	DTOs"
        [[params.information.list.items]]
        details = "•	Controllers as the way to send requests from frontend and to receive response from backend"

        [[params.information.list]]
        title = "Basic programming concepts"
        [[params.information.list.items]]
        details = "•	Create and initialize variables"
        [[params.information.list.items]]
        details = "•	Loops, arrays"
        [[params.information.list.items]]
        details = "•	Array sorting types"
        [[params.information.list.items]]
        details = "•	Java best practices (Java Code Convention)"

        [[params.information.list]]
        title = "The OOP concepts"
        [[params.information.list.items]]
        details = "•	Abstraction"
        [[params.information.list.items]]
        details = "•	Encapsulation"
        [[params.information.list.items]]
        details = "•	Inheritance"
        [[params.information.list.items]]
        details = "•	Polymorphism"

        [[params.information.list]]
        title = "Java Professional"
        [[params.information.list.items]]
        details = "•	Java Framework Collection"
        [[params.information.list.items]]
        details = "•	Lambda"
        [[params.information.list.items]]
        details = "•	Stream API"

        [[params.information.list]]
        title = "SQL and MySQL"
        [[params.information.list.items]]
        details = "•	Draw ERD data models with foreign and primary keys, one-to-one, one-to-many relationships, etc."
        [[params.information.list.items]]
        details = "•	Create BD, tables, request types, stored procedures, join tables, transactions"
        [[params.information.list.items]]
        details = "•	Create small projects using DAO and JDBC API"

        [[params.information.list]]
        title = "Backend development"
        [[params.information.list.items]]
        details = "•	Hibernate and Spring"
        [[params.information.list.items]]
        details = "•	Hibernate query types"
        [[params.information.list.items]]
        details = "•	Local Tomcat server"
        [[params.information.list.items]]
        details = "•	Servlet API"

        [[params.information.list]]
        title = "Final steps with Spring MVC"
        [[params.information.list.items]]
        details = "•	Create a web project and set up Spring Security"
        [[params.information.list.items]]
        details = "•	Implement dependencies in Apache Maven"
        [[params.information.list.items]]
        details = "•	Store data in the DB using a JPA repository"
        [[params.information.list.items]]
        details = "•	Implement Controllers on the backend side and show data on the client side using Thymeleaf and Bootstrap"
        [[params.information.list.items]]
        details = "•	Full stack web developer with Angular framework"
        [[params.information.list.items]]
        details = "•	Participate in the commercial project"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/eduardvitko"
        title = "Eduard Vitko"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/eduard-vitko-a03163188"
        title = "Eduard Vitko profile"
        #[[params.social.list]]
        #icon = "fab fa-twitter-square"
        #url = "//twitter.com/username"
        #title = "@username"





